/**
 * Dicionário Completo de Traduções (i18n)
 * Idiomas: PT, EN, ES, FR, IT
 */
const translations = {
  pt: {
    doc_title: "Minha Carreira Em Um Site!",
    nav_about: "Sobre mim",
    nav_projects: "Projetos",
    nav_contact: "Contato",
    nav_skills: "Habilidades Técnicas",
    nav_achievements: "Conquistas",
    nav_github: "Github",
    header_role: "Analista de Suporte a Sistemas Jr",
    header_subtitle_text: "Especialista em SRE & DevOps na Vivo (Telefônica Brasil)",
    status_online: "SYSTEM ONLINE",
    core_title: "> Core & Metodologias",
    obs_title: "> Observabilidade & Monitoramento",
    tag_monit: "Monitoramento",
    auto_title: "> Automação & Continuous Delivery",
    tag_auto: "Automação",
    infra_title: "> Infraestrutura & Base",
    tag_infra: "Infraestrutura",
    download_cv: "Baixar Currículo!",
    about_title: "Sobre mim",
    about_p1: "Minha trajetória na área de Tecnologia da Informação começou com minha formação técnica em Informática e Tecnologia da Informação pela Megatoc, onde construí minha base em desenvolvimento, infraestrutura, sistemas e suporte tecnológico.",
    about_p2: "Ao longo de aproximadamente <strong>3 anos de experiência na Vivo (Telefônica Brasil)</strong>, iniciei minha carreira como Jovem Aprendiz em Infraestrutura de Sistemas, no Command Center (Equipe de Produção - B2C), evoluindo posteriormente para Estagiário de Sistemas na Gerência de Observabilidade, com atuação junto ao <strong>Emergency Response Team (ERT)</strong>.",
    about_p3: "Durante essa jornada, atuei em <strong>ambientes críticos de produção</strong>, desenvolvendo experiência em observabilidade, monitoramento, resposta a incidentes, análise de logs, gestão de problemas, automação e práticas de <strong>Site Reliability Engineering (SRE)</strong>.",
    about_p4: "Minha atuação combina conhecimentos de <strong>desenvolvimento de software, infraestrutura, observabilidade e automação</strong>, buscando transformar processos operacionais em soluções mais eficientes, confiáveis e escaláveis.",
    about_p5: "Atualmente, direciono minha formação para <strong>Engenharia de Software</strong>, aprofundando conhecimentos em desenvolvimento Full-Stack, arquitetura de sistemas, Cloud, bancos de dados, segurança, metodologias ágeis e <strong>Inteligência Artificial</strong>.",
    about_p6: "Tenho como objetivo continuar evoluindo profissionalmente na interseção entre <strong>Software, SRE, Observabilidade, Automação e Cloud</strong>, utilizando tecnologia para resolver problemas reais, otimizar processos e aumentar a confiabilidade dos ambientes e sistemas.",
    edu_title: "Formação",
    edu_c1_inst: "Universidade Nove de Julho",
    edu_c1_title: "Tecnólogo em Análise e Desenvolvimento de Sistemas",
    edu_c1_period: "jan de 2025 – ago de 2027",
    edu_c1_p1: "Formação voltada à <strong>análise, desenvolvimento e implementação de sistemas computacionais</strong>, proporcionando uma base sólida em programação, engenharia de software, modelagem de dados, arquitetura de sistemas e desenvolvimento de soluções.",
    edu_c1_p2: "Ao longo da graduação, desenvolvi projetos acadêmicos e práticos utilizando tecnologias como <strong>Java, Python e SQL</strong>, trabalhando desde a análise e planejamento até o desenvolvimento e validação de aplicações.",
    edu_c1_p3: "Também desenvolvi conhecimentos em <strong>Scrum e Kanban</strong>, aplicados à organização e gestão de projetos, além de práticas de desenvolvimento, resolução de problemas e trabalho colaborativo.",
    edu_c1_p4: "A formação também proporcionou contato com temas como <strong>Inteligência Artificial, desenvolvimento mobile e segurança da informação</strong>, ampliando minha visão sobre diferentes áreas do ecossistema de tecnologia.",
    edu_skills_title: "Principais competências:",
    edu_c1_k1: "Programação e desenvolvimento de sistemas",
    edu_c1_k2: "Java, Python e SQL",
    edu_c1_k3: "Modelagem e desenvolvimento de bancos de dados",
    edu_c1_k4: "Engenharia e arquitetura de software",
    edu_c1_k5: "Scrum e Kanban",
    edu_c1_k6: "Resolução e otimização de problemas computacionais",
    edu_c1_k7: "Desenvolvimento de projetos de software",
    edu_c1_k8: "Inteligência Artificial e novas tecnologias",
    edu_c1_k9: "Desenvolvimento mobile",
    edu_c1_k10: "Segurança da informação",
    edu_c2_inst: "Cruzeiro do Sul Virtual",
    edu_c2_title: "Bacharelado em Engenharia de Software",
    edu_c2_period: "jan de 2026 – dez de 2029",
    edu_c2_p1: "Minha formação em <strong>Engenharia de Software</strong> tem como objetivo aprofundar conhecimentos técnicos e desenvolver uma visão completa sobre o <strong>ciclo de vida do desenvolvimento de software (SDLC)</strong>, desde a concepção e arquitetura até desenvolvimento, testes, segurança e evolução de sistemas.",
    edu_c2_p2: "A formação aborda conceitos de <strong>arquitetura de sistemas escaláveis, desenvolvimento Full-Stack, Cloud Computing, bancos de dados, qualidade de software, segurança, metodologias ágeis e Inteligência Artificial</strong>.",
    edu_areas_title: "Principais áreas de conhecimento:",
    edu_c2_k1: "<strong>Desenvolvimento Full-Stack:</strong> desenvolvimento de aplicações Web e Mobile, abrangendo Front-End, Back-End, arquitetura de aplicações e boas práticas de desenvolvimento.",
    edu_c2_k2: "<strong>Dados e Sistemas de Informação:</strong> modelagem de dados, bancos de dados, Ciência de Dados e desenvolvimento de Sistemas de Informação.",
    edu_c2_k3: "<strong>Arquitetura e Cloud:</strong> fundamentos de computação em nuvem, escalabilidade, disponibilidade, arquitetura de sistemas e desenvolvimento de aplicações resilientes.",
    edu_c2_k4: "<strong>Qualidade e Segurança:</strong> testes de software, qualidade, segurança em ambientes digitais, integridade, performance e confiabilidade.",
    edu_c2_k5: "<strong>Metodologias e Gestão:</strong> aplicação de metodologias ágeis e conceitos de gestão de projetos, incluindo Scrum e Kanban.",
    edu_c2_k6: "<strong>Inteligência Artificial:</strong> Engenharia de Prompt e aplicações de IA voltadas ao desenvolvimento, automação e otimização de processos.",
    edu_c2_p3: "Durante a formação, desenvolvi uma <strong>ferramenta de automação para monitoramento da saúde e disponibilidade de ambientes de produção</strong>, com foco em servidores WebLogic e filas de processamento.",
    edu_c2_p4: "O projeto transformou um processo de inspeção manual em uma rotina automatizada, proporcionando uma redução significativa no tempo necessário para a execução do procedimento.",
    edu_kpi_title: "Resultado e Impacto (KPI)",
    edu_kpi_val: "1 hora → 5 minutos",
    edu_kpi_desc: "Redução de aproximadamente <strong>92% no tempo de inspeção</strong> por meio da execução automatizada.",
    edu_skills_dev: "Competências desenvolvidas:",
    edu_c2_s1: "Design de Interfaces (UX/UI)",
    edu_c2_s2: "Computação em Nuvem",
    edu_c2_s3: "Testes de Software — Unitários e Funcionais",
    edu_c2_s4: "Planejamento e Arquitetura de Sistemas",
    edu_c2_s5: "Desenvolvimento Front-End e Back-End",
    edu_c2_s6: "Automação de Sistemas",
    edu_c2_s7: "Qualidade de Software",
    edu_c2_s8: "Segurança de Aplicações",
    edu_c2_s9: "Inteligência Artificial",
    edu_c2_s10: "Metodologias Ágeis",
    courses_title: "Cursos",
    courses_p1: "Ao longo da minha trajetória, busquei constantemente aprimorar meus conhecimentos técnicos e comportamentais por meio de formações complementares. Concluí diversos cursos em plataformas reconhecidas como <strong>Alura</strong>, <strong>Fundação Bradesco</strong>, <strong>LinkedIn Learning</strong>, <strong>Enabley UK & ROI</strong>, <strong>Vivae</strong> e também pela <strong>Vivo (Telefônica Brasil)</strong>, abrangendo áreas essenciais da tecnologia e do desenvolvimento profissional.",
    courses_topics_title: "Entre os principais temas estudados estão:",
    courses_t1: "<strong>Programação e Desenvolvimento:</strong> lógica com JavaScript, desenvolvimento back-end em Java, fundamentos de POO, criação de jogos, Git e GitHub, API e integração contínua.",
    courses_t2: "<strong>Infraestrutura e DevOps:</strong> PowerShell, Docker, Linux (terminal, processos, permissões, CLI), Windows Prompt, redes, ServiceNow, Zabbix, Elastic e Datadog.",
    courses_t3: "<strong>Orquestração e Contêineres:</strong> Kubernetes (Pods, Services, ConfigMaps, Deployments e Escalabilidade).",
    courses_t4: "<strong>Banco de Dados:</strong> fundamentos de SQL e gestão de dados.",
    courses_t5: "<strong>Metodologias Ágeis e Soft Skills:</strong> Scrum/Kanban, postura profissional, controle de impulso, habilidades comportamentais e diversidade.",
    courses_t6: "<strong>Fundamentos de TI:</strong> sistemas operacionais, engenharia de redes móveis, SDLC (ciclo de vida do desenvolvimento de software), diferenças entre front-end e back-end e carreira de programador.",
    courses_p2: "Esses cursos reforçam meu compromisso com a aprendizagem contínua e me proporcionam uma base sólida para atuar com eficiência em projetos de tecnologia, infraestrutura e desenvolvimento de software.",
    exp_title: "Experiência",
    exp1_role: "Estagiário de Sistema - Observabilidade & ERT (SRE)",
    exp1_period: "mar de 2025 – o momento · 1 Ano e 7 Meses",
    exp1_location: "São Paulo, Brasil · Híbrida",
    exp1_desc: "Atuação como Estagiário de Sistemas na Gerência de Observabilidade, integrando a equipe de Respostas Emergenciais B2C (ERT). Experiência direcionada à confiabilidade de ambientes críticos, observabilidade, automação, análise de incidentes e melhoria contínua dos processos operacionais.",
    exp1_t1: "Desenvolvimento e evolução de <strong>alarmes e dashboards</strong> utilizando ServiceNow, Elastic e Zabbix.",
    exp1_t2: "Monitoramento de ambientes críticos e análise de <strong>métricas, eventos e logs</strong> para identificação e diagnóstico de falhas.",
    exp1_t3: "Participação na <strong>resposta a incidentes críticos B2C</strong>, apoiando as etapas de investigação, diagnóstico e resolução.",
    exp1_t4: "Realização de <strong>análises de causa raiz (RCA)</strong> para investigação de falhas e problemas recorrentes.",
    exp1_t5: "Atuação na gestão e evolução de <strong>PRBs (Problem Records)</strong>, contribuindo para a identificação e tratamento de causas recorrentes.",
    exp1_t6: "Desenvolvimento de <strong>workflows para alertas de problemas críticos</strong>, contribuindo para maior agilidade e eficiência operacional.",
    exp1_t7: "Desenvolvimento de automações e aplicações web utilizando <strong>HTML, CSS e JavaScript</strong>.",
    exp1_t8: "Desenvolvimento de um <strong>Health Check automatizado</strong> para validação da saúde e disponibilidade dos servidores.",
    exp1_t9: "Desenvolvimento de soluções para acompanhamento de <strong>servidores WebLogic e filas de processamento</strong>.",
    exp1_t10: "Administração operacional de ambientes utilizando <strong>Oracle Server e Jenkins</strong>.",
    exp1_t11: "Execução de procedimentos de <strong>Stop/Start, limpeza de cache, análise de logs e validação de componentes</strong> em ambientes de produção.",
    exp1_t12: "Criação de <strong>SharePoint para gestão de projetos em produção e treinamento de colaboradores</strong>.",
    exp1_t13: "Desenvolvimento de páginas e ferramentas web para facilitar a integração entre equipes de <strong>Projetos, Operações e Product Owners</strong>.",
    exp1_t14: "Atuação como referência na <strong>qualidade de PRBs</strong>, realizando análises, feedbacks e treinamentos para aprimorar a padronização e maturidade da Gestão de Problemas.",
    exp1_t15: "Desenvolvimento de soluções voltadas à <strong>automação e otimização de processos operacionais</strong>, reduzindo atividades manuais e aumentando a eficiência da equipe.",
    exp2_role: "Jovem Aprendiz - Infraestrutura de Sistemas (PCP)",
    exp2_period: "set de 2023 – mar de 2025 · 1 ano e 7 meses",
    exp2_location: "São Paulo, Brasil · Híbrida",
    exp2_desc: "Minha primeira experiência profissional em Tecnologia foi na Vivo, atuando na área de Infraestrutura de Sistemas, no Command Center (PCP B2C). Nesse período, desenvolvi uma base sólida em monitoramento, observabilidade, infraestrutura, análise de incidentes e suporte à operação de ambientes críticos.",
    exp2_t1: "Monitoramento de ambientes B2C utilizando <strong>Grafana, Dynatrace, Elastic, Kibana, Splunk e Zabbix</strong>.",
    exp2_t2: "Análise de <strong>métricas, eventos e logs</strong> para identificação e diagnóstico de falhas.",
    exp2_t3: "Gerenciamento e acompanhamento de <strong>jobs e malhas de processamento no Control-M</strong>.",
    exp2_t4: "Extração de relatórios e gerenciamento de acessos utilizando <strong>SiTef Web</strong>.",
    exp2_t5: "Tratamento e acompanhamento de solicitações e incidentes através do <strong>ServiceNow</strong>.",
    exp2_t6: "Execução de <strong>checklists operacionais diários</strong> para validação da saúde dos ambientes.",
    exp2_t7: "Monitoramento dos processos de <strong>Recovery da Portabilidade em ambientes Linux</strong>, acompanhando logs e filas de processamento.",
    exp2_t8: "Acompanhamento do processamento das filas referentes aos ambientes de <strong>São Paulo e demais regiões do Brasil</strong>.",
    exp2_t9: "Validação de <strong>componentes e nodes do Siebel</strong>, contribuindo para a estabilidade e disponibilidade do sistema.",
    exp2_t10: "Comunicação e escalonamento de <strong>alertas operacionais</strong> para as equipes responsáveis.",
    exp2_t11: "Análise e tratamento de problemas, utilizando informações de <strong>logs e indicadores</strong> para apoiar a identificação da causa raiz.",
    exp2_t12: "Criação e manutenção de <strong>documentações, automações e fluxos operacionais</strong>.",
    exp2_t13: "Apoio na integração e <strong>treinamento de novos colaboradores</strong>, compartilhando conhecimentos sobre sistemas internos e processos de monitoramento.",
    exp2_t14: "Acesso e operação de <strong>ambientes Linux</strong> para análise de logs e acompanhamento de processos de recuperação.",
    exp2_t15: "Acompanhamento da saúde dos ambientes e comunicação de ocorrências para suporte à continuidade da operação.",
    footer_rights: "© 2026 • Portfólio de Kauê Rodrigues Mirom • TI • São Paulo, Brasil"
  },
  en: {
    doc_title: "My Career On A Website!",
    nav_about: "About me",
    nav_projects: "Projects",
    nav_contact: "Contact",
    nav_skills: "Technical Skills",
    nav_achievements: "Achievements",
    nav_github: "Github",
    header_role: "Jr System Support Analyst",
    header_subtitle_text: "SRE & DevOps Specialist at Vivo (Telefônica Brasil)",
    status_online: "SYSTEM ONLINE",
    core_title: "> Core & Methodologies",
    obs_title: "> Observability & Monitoring",
    tag_monit: "Monitoring",
    auto_title: "> Automation & Continuous Delivery",
    tag_auto: "Automation",
    infra_title: "> Infrastructure & Core",
    tag_infra: "Infrastructure",
    download_cv: "Download Resume!",
    about_title: "About me",
    about_p1: "My journey in Information Technology began with my technical training in IT and Information Technology at Megatoc, where I built my foundation in development, infrastructure, systems, and tech support.",
    about_p2: "Over approximately <strong>3 years of experience at Vivo (Telefônica Brasil)</strong>, I started my career as a Young Apprentice in Systems Infrastructure at the Command Center (Production Team - B2C), later evolving to Systems Intern in Observability Management, working with the <strong>Emergency Response Team (ERT)</strong>.",
    about_p3: "During this journey, I worked in <strong>critical production environments</strong>, developing experience in observability, monitoring, incident response, log analysis, problem management, automation, and <strong>Site Reliability Engineering (SRE)</strong> practices.",
    about_p4: "My work combines knowledge of <strong>software development, infrastructure, observability, and automation</strong>, aiming to transform operational processes into more efficient, reliable, and scalable solutions.",
    about_p5: "Currently, I am focusing my education on <strong>Software Engineering</strong>, deepening my knowledge in Full-Stack development, systems architecture, Cloud, databases, security, agile methodologies, and <strong>Artificial Intelligence</strong>.",
    about_p6: "My goal is to continue evolving professionally at the intersection of <strong>Software, SRE, Observability, Automation, and Cloud</strong>, using technology to solve real problems, optimize processes, and increase system reliability.",
    edu_title: "Education",
    edu_c1_inst: "Nove de Julho University",
    edu_c1_title: "Associate Degree in Systems Analysis and Development",
    edu_c1_period: "Jan 2025 – Aug 2027",
    edu_c1_p1: "Degree focused on <strong>analysis, development, and implementation of computing systems</strong>, providing a solid foundation in programming, software engineering, data modeling, systems architecture, and solution development.",
    edu_c1_p2: "Throughout the course, I developed academic and practical projects using technologies like <strong>Java, Python, and SQL</strong>, working from analysis and planning to application development and validation.",
    edu_c1_p3: "I also gained knowledge in <strong>Scrum and Kanban</strong>, applied to project management, alongside development practices, problem-solving, and collaborative work.",
    edu_c1_p4: "The program provided exposure to topics such as <strong>Artificial Intelligence, mobile development, and information security</strong>, expanding my view across different areas of the tech ecosystem.",
    edu_skills_title: "Core competencies:",
    edu_c1_k1: "Programming and systems development",
    edu_c1_k2: "Java, Python, and SQL",
    edu_c1_k3: "Database modeling and development",
    edu_c1_k4: "Software engineering and architecture",
    edu_c1_k5: "Scrum and Kanban",
    edu_c1_k6: "Solving and optimizing computational problems",
    edu_c1_k7: "Software project development",
    edu_c1_k8: "Artificial Intelligence and new technologies",
    edu_c1_k9: "Mobile development",
    edu_c1_k10: "Information security",
    edu_c2_inst: "Cruzeiro do Sul Virtual",
    edu_c2_title: "Bachelor's Degree in Software Engineering",
    edu_c2_period: "Jan 2026 – Dec 2029",
    edu_c2_p1: "My degree in <strong>Software Engineering</strong> aims to deepen technical knowledge and build a comprehensive view of the <strong>Software Development Life Cycle (SDLC)</strong>, from design and architecture to development, testing, security, and evolution.",
    edu_c2_p2: "The curriculum covers <strong>scalable systems architecture, Full-Stack development, Cloud Computing, databases, software quality, security, agile methodologies, and Artificial Intelligence</strong>.",
    edu_areas_title: "Main knowledge areas:",
    edu_c2_k1: "<strong>Full-Stack Development:</strong> Web and Mobile app development, covering Front-End, Back-End, application architecture, and best practices.",
    edu_c2_k2: "<strong>Data and Information Systems:</strong> data modeling, databases, Data Science, and Information Systems development.",
    edu_c2_k3: "<strong>Architecture and Cloud:</strong> cloud computing fundamentals, scalability, availability, systems architecture, and resilient application development.",
    edu_c2_k4: "<strong>Quality and Security:</strong> software testing, quality, digital environment security, integrity, performance, and reliability.",
    edu_c2_k5: "<strong>Methodologies and Management:</strong> application of agile methodologies and project management concepts, including Scrum and Kanban.",
    edu_c2_k6: "<strong>Artificial Intelligence:</strong> Prompt Engineering and AI applications focused on development, automation, and process optimization.",
    edu_c2_p3: "During this program, I developed an <strong>automation tool to monitor health and availability in production environments</strong>, focusing on WebLogic servers and processing queues.",
    edu_c2_p4: "The project turned a manual inspection process into an automated routine, significantly reducing execution time.",
    edu_kpi_title: "Result and Impact (KPI)",
    edu_kpi_val: "1 hour → 5 minutes",
    edu_kpi_desc: "Approximately <strong>92% reduction in inspection time</strong> through automated execution.",
    edu_skills_dev: "Developed skills:",
    edu_c2_s1: "Interface Design (UX/UI)",
    edu_c2_s2: "Cloud Computing",
    edu_c2_s3: "Software Testing — Unit & Functional",
    edu_c2_s4: "Systems Planning and Architecture",
    edu_c2_s5: "Front-End and Back-End Development",
    edu_c2_s6: "Systems Automation",
    edu_c2_s7: "Software Quality",
    edu_c2_s8: "Application Security",
    edu_c2_s9: "Artificial Intelligence",
    edu_c2_s10: "Agile Methodologies",
    courses_title: "Courses",
    courses_p1: "Throughout my career, I continuously sought to refine my technical and soft skills through complementary training. I completed various courses on platforms like <strong>Alura</strong>, <strong>Fundação Bradesco</strong>, <strong>LinkedIn Learning</strong>, <strong>Enabley UK & ROI</strong>, <strong>Vivae</strong>, and <strong>Vivo (Telefônica Brasil)</strong>, covering essential areas of technology and professional development.",
    courses_topics_title: "Main topics studied include:",
    courses_t1: "<strong>Programming & Development:</strong> JavaScript logic, Java back-end development, OOP fundamentals, game creation, Git & GitHub, API, and CI.",
    courses_t2: "<strong>Infrastructure & DevOps:</strong> PowerShell, Docker, Linux (terminal, processes, permissions, CLI), Windows Prompt, networks, ServiceNow, Zabbix, Elastic, and Datadog.",
    courses_t3: "<strong>Orchestration & Containers:</strong> Kubernetes (Pods, Services, ConfigMaps, Deployments, and Scalability).",
    courses_t4: "<strong>Databases:</strong> SQL fundamentals and data management.",
    courses_t5: "<strong>Agile Methodologies & Soft Skills:</strong> Scrum/Kanban, professional demeanor, impulse control, soft skills, and diversity.",
    courses_t6: "<strong>IT Fundamentals:</strong> operating systems, mobile network engineering, SDLC, front-end vs back-end, and developer career pathways.",
    courses_p2: "These courses reinforce my commitment to continuous learning and provide a solid foundation to work efficiently in technology, infrastructure, and software development projects.",
    exp_title: "Experience",
    exp1_role: "Systems Intern - Observability & ERT (SRE)",
    exp1_period: "Mar 2025 – Present · 1 Year 7 Months",
    exp1_location: "São Paulo, Brazil · Hybrid",
    exp1_desc: "Acting as Systems Intern in Observability Management, part of the Emergency Response Team (ERT) B2C. Focused on critical environment reliability, observability, automation, incident analysis, and continuous process improvement.",
    exp1_t1: "Development and enhancement of <strong>alerts and dashboards</strong> using ServiceNow, Elastic, and Zabbix.",
    exp1_t2: "Monitoring critical environments and analyzing <strong>metrics, events, and logs</strong> to identify and diagnose failures.",
    exp1_t3: "Participation in <strong>critical B2C incident response</strong>, supporting investigation, diagnosis, and resolution.",
    exp1_t4: "Conducting <strong>Root Cause Analysis (RCA)</strong> to investigate recurring issues and failures.",
    exp1_t5: "Managing and advancing <strong>PRBs (Problem Records)</strong>, helping identify and address root causes.",
    exp1_t6: "Developing <strong>workflows for critical alerts</strong>, improving operational agility and efficiency.",
    exp1_t7: "Building web automations and applications using <strong>HTML, CSS, and JavaScript</strong>.",
    exp1_t8: "Developing an <strong>automated Health Check</strong> to validate server health and availability.",
    exp1_t9: "Building solutions to track <strong>WebLogic servers and processing queues</strong>.",
    exp1_t10: "Operational administration using <strong>Oracle Server and Jenkins</strong>.",
    exp1_t11: "Executing <strong>Stop/Start, cache clearing, log analysis, and component validation</strong> in production.",
    exp1_t12: "Creating a <strong>SharePoint for production project management and employee training</strong>.",
    exp1_t13: "Developing web tools to streamline integration between <strong>Projects, Operations, and Product Owners</strong>.",
    exp1_t14: "Serving as a reference for <strong>PRB quality</strong>, conducting analysis and training to increase Problem Management maturity.",
    exp1_t15: "Developing solutions for <strong>automation and optimization of operational processes</strong>, reducing manual effort.",
    exp2_role: "Young Apprentice - Systems Infrastructure (PCP)",
    exp2_period: "Sep 2023 – Mar 2025 · 1 year 7 months",
    exp2_location: "São Paulo, Brazil · Hybrid",
    exp2_desc: "My first professional experience in Tech was at Vivo, in Systems Infrastructure at the Command Center (PCP B2C). Built a solid foundation in monitoring, observability, infrastructure, incident analysis, and critical operations support.",
    exp2_t1: "Monitoring B2C environments using <strong>Grafana, Dynatrace, Elastic, Kibana, Splunk, and Zabbix</strong>.",
    exp2_t2: "Analyzing <strong>metrics, events, and logs</strong> for fault identification and diagnosis.",
    exp2_t3: "Managing and tracking <strong>jobs and processing batches in Control-M</strong>.",
    exp2_t4: "Extracting reports and managing access via <strong>SiTef Web</strong>.",
    exp2_t5: "Handling and following up on requests and incidents using <strong>ServiceNow</strong>.",
    exp2_t6: "Executing <strong>daily operational checklists</strong> to validate environment health.",
    exp2_t7: "Monitoring <strong>Number Portability Recovery processes in Linux environments</strong>, tracking logs and queues.",
    exp2_t8: "Tracking processing queues for <strong>São Paulo and other regions in Brazil</strong>.",
    exp2_t9: "Validating <strong>Siebel components and nodes</strong>, contributing to system availability.",
    exp2_t10: "Communicating and escalating <strong>operational alerts</strong> to responsible teams.",
    exp2_t11: "Analyzing issues using <strong>logs and metrics</strong> to assist in root cause identification.",
    exp2_t12: "Creating and maintaining <strong>documentation, automations, and operational workflows</strong>.",
    exp2_t13: "Supporting onboarding and <strong>training new team members</strong> on internal systems and monitoring tools.",
    exp2_t14: "Operating in <strong>Linux environments</strong> for log analysis and recovery tracking.",
    exp2_t15: "Monitoring overall environment health and reporting events to ensure operational continuity.",
    footer_rights: "© 2026 • Kauê Rodrigues Mirom Portfolio • IT • São Paulo, Brazil"
  },
  es: {
    doc_title: "¡Mi Carrera En Un Sitio Web!",
    nav_about: "Sobre mí",
    nav_projects: "Proyectos",
    nav_contact: "Contacto",
    nav_skills: "Habilidades Técnicas",
    nav_achievements: "Logros",
    nav_github: "Github",
    header_role: "Analista de Soporte a Sistemas Jr",
    header_subtitle_text: "Especialista en SRE & DevOps en Vivo (Telefônica Brasil)",
    status_online: "SYSTEM ONLINE",
    core_title: "> Core & Metodologías",
    obs_title: "> Observabilidad & Monitoreo",
    tag_monit: "Monitoreo",
    auto_title: "> Automatización & Continuous Delivery",
    tag_auto: "Automatización",
    infra_title: "> Infraestructura & Base",
    tag_infra: "Infraestructura",
    download_cv: "¡Descargar Currículum!",
    about_title: "Sobre mí",
    about_p1: "Mi trayectoria en Tecnologías de la Información comenzó con mi formación técnica en Informática y TI en Megatoc, donde construí mis bases en desarrollo, infraestructura, sistemas y soporte técnico.",
    about_p2: "A lo largo de aproximadamente <strong>3 años de experiencia en Vivo (Telefônica Brasil)</strong>, inicié mi carrera como Joven Aprendiz en Infraestructura de Sistemas en el Command Center (B2C), evolucionando a Pasante de Sistemas en la Gerencia de Observabilidad con el <strong>Emergency Response Team (ERT)</strong>.",
    about_p3: "Durante este recorrido, trabajé en <strong>entornos de producción críticos</strong>, desarrollando experiencia en observabilidad, monitoreo, respuesta a incidentes, análisis de logs, gestión de problemas, automatización y prácticas de <strong>Site Reliability Engineering (SRE)</strong>.",
    about_p4: "Mi enfoque combina conocimientos de <strong>desarrollo de software, infraestructura, observabilidad y automatización</strong> para transformar procesos operativos en soluciones eficientes y escalables.",
    about_p5: "Actualmente, mi orientación académica se enfoca en <strong>Ingeniería de Software</strong>, profundizando en desarrollo Full-Stack, arquitectura de sistemas, Cloud, bases de datos, seguridad, metodologías ágiles e <strong>Inteligencia Artificial</strong>.",
    about_p6: "Mi objetivo es seguir evolucionando en la intersección entre <strong>Software, SRE, Observabilidad, Automatización y Cloud</strong>, usando la tecnología para resolver problemas reales y optimizar procesos.",
    edu_title: "Educación",
    edu_c1_inst: "Universidad Nove de Julho",
    edu_c1_title: "Tecnólogo en Análisis y Desarrollo de Sistemas",
    edu_c1_period: "ene de 2025 – ago de 2027",
    edu_c1_p1: "Formación orientada al <strong>análisis, desarrollo e implementación de sistemas informáticos</strong>, brindando una base sólida en programación, ingeniería de software y desarrollo de soluciones.",
    edu_c1_p2: "Desarrollé proyectos académicos y prácticos utilizando <strong>Java, Python y SQL</strong>, abarcando desde la planificación hasta la validación de aplicaciones.",
    edu_c1_p3: "Adquirí conocimientos en <strong>Scrum y Kanban</strong> aplicados a la gestión de proyectos, resolución de problemas y trabajo colaborativo.",
    edu_c1_p4: "La carrera incluyó contacto con <strong>Inteligencia Artificial, desarrollo móvil y seguridad de la información</strong>.",
    edu_skills_title: "Competencias clave:",
    edu_c1_k1: "Programación y desarrollo de sistemas",
    edu_c1_k2: "Java, Python y SQL",
    edu_c1_k3: "Modelado y desarrollo de bases de datos",
    edu_c1_k4: "Ingeniería y arquitectura de software",
    edu_c1_k5: "Scrum y Kanban",
    edu_c1_k6: "Resolución de problemas computacionales",
    edu_c1_k7: "Desarrollo de proyectos de software",
    edu_c1_k8: "Inteligencia Artificial y nuevas tecnologías",
    edu_c1_k9: "Desarrollo móvil",
    edu_c1_k10: "Seguridad de la información",
    edu_c2_inst: "Cruzeiro do Sul Virtual",
    edu_c2_title: "Grado en Ingeniería de Software",
    edu_c2_period: "ene de 2026 – dic de 2029",
    edu_c2_p1: "Mi formación en <strong>Ingeniería de Software</strong> busca profundizar en conocimientos técnicos y ciclo de vida del software (SDLC).",
    edu_c2_p2: "Aborda <strong>arquitectura escalable, desarrollo Full-Stack, Cloud Computing, bases de datos, calidad, seguridad, metodologías ágiles e IA</strong>.",
    edu_areas_title: "Áreas clave de conocimiento:",
    edu_c2_k1: "<strong>Desarrollo Full-Stack:</strong> desarrollo web y móvil, Front-End, Back-End y buenas prácticas.",
    edu_c2_k2: "<strong>Datos y Sistemas:</strong> modelado de datos, bases de datos y Ciencia de Datos.",
    edu_c2_k3: "<strong>Arquitectura y Cloud:</strong> computación en la nube, escalabilidad y resiliencia.",
    edu_c2_k4: "<strong>Calidad y Seguridad:</strong> pruebas de software, seguridad digital y rendimiento.",
    edu_c2_k5: "<strong>Metodologías:</strong> aplicación de marcos ágiles como Scrum y Kanban.",
    edu_c2_k6: "<strong>Inteligencia Artificial:</strong> Ingeniería de Prompts e integración de IA en procesos.",
    edu_c2_p3: "Desarrollé una <strong>herramienta automatizada para monitorear servidores WebLogic y colas de procesamiento</strong>.",
    edu_c2_p4: "El proyecto transformó una inspección manual en una rutina automática, reduciendo enormemente los tiempos.",
    edu_kpi_title: "Resultado e Impacto (KPI)",
    edu_kpi_val: "1 hora → 5 minutos",
    edu_kpi_desc: "Reducción aproximada del <strong>92% en tiempo de inspección</strong>.",
    edu_skills_dev: "Competencias desarrolladas:",
    edu_c2_s1: "Diseño de Interfaces (UX/UI)",
    edu_c2_s2: "Computación en la Nube",
    edu_c2_s3: "Pruebas de Software — Unitarias y Funcionales",
    edu_c2_s4: "Planificación y Arquitectura de Sistemas",
    edu_c2_s5: "Desarrollo Front-End y Back-End",
    edu_c2_s6: "Automatización de Sistemas",
    edu_c2_s7: "Calidad de Software",
    edu_c2_s8: "Seguridad de Aplicaciones",
    edu_c2_s9: "Inteligencia Artificial",
    edu_c2_s10: "Metodologías Ágiles",
    courses_title: "Cursos",
    courses_p1: "Completé múltiples cursos en plataformas como <strong>Alura</strong>, <strong>Fundação Bradesco</strong>, <strong>LinkedIn Learning</strong>, <strong>Enabley UK & ROI</strong>, <strong>Vivae</strong> y <strong>Vivo</strong>.",
    courses_topics_title: "Principales temas estudiados:",
    courses_t1: "<strong>Programación:</strong> lógica JS, Java back-end, POO, Git/GitHub y CI.",
    courses_t2: "<strong>Infraestructura & DevOps:</strong> PowerShell, Docker, Linux, redes, ServiceNow, Zabbix y Elastic.",
    courses_t3: "<strong>Orquestación:</strong> Kubernetes (Pods, Services, Deployments).",
    courses_t4: "<strong>Bases de Datos:</strong> fundamentos de SQL y gestión de datos.",
    courses_t5: "<strong>Agile & Soft Skills:</strong> Scrum/Kanban, comunicación y trabajo en equipo.",
    courses_t6: "<strong>Fundamentos TI:</strong> Sistemas Operativos, redes móviles y carrera de desarrollador.",
    courses_p2: "Estos cursos fortalecen mi compromiso con el aprendizaje continuo.",
    exp_title: "Experiencia",
    exp1_role: "Pasante de Sistemas - Observabilidad & ERT (SRE)",
    exp1_period: "mar de 2025 – presente · 1 Año y 7 Meses",
    exp1_location: "São Paulo, Brasil · Híbrida",
    exp1_desc: "Actuación como pasante en la Gerencia de Observabilidad (ERT B2C), enfocado en confiabilidad, automatización y análisis de incidentes.",
    exp1_t1: "Desarrollo de <strong>alarmas y dashboards</strong> en ServiceNow, Elastic y Zabbix.",
    exp1_t2: "Monitoreo de ambientes críticos y análisis de <strong>métricas, eventos y logs</strong>.",
    exp1_t3: "Participación en la <strong>respuesta a incidentes críticos B2C</strong>.",
    exp1_t4: "Análisis de causa raíz <strong>(RCA)</strong> para fallas recurrentes.",
    exp1_t5: "Gestión y evolución de registros de problemas <strong>(PRBs)</strong>.",
    exp1_t6: "Creación de <strong>workflows de alertas críticas</strong>.",
    exp1_t7: "Desarrollo web y automatizaciones con <strong>HTML, CSS y JavaScript</strong>.",
    exp1_t8: "Creación de un <strong>Health Check automatizado</strong> para servidores.",
    exp1_t9: "Herramientas para monitoreo de <strong>WebLogic y colas de procesamiento</strong>.",
    exp1_t10: "Administración operacional con <strong>Oracle Server y Jenkins</strong>.",
    exp1_t11: "Ejecución de <strong>Stop/Start y análisis de logs</strong> en producción.",
    exp1_t12: "Creación de <strong>SharePoint para gestión de proyectos</strong>.",
    exp1_t13: "Herramientas web para integrar <strong>Proyectos y Product Owners</strong>.",
    exp1_t14: "Capacitación y feedback sobre <strong>calidad de PRBs</strong>.",
    exp1_t15: "Automatización de procesos para reducción de trabajo manual.",
    exp2_role: "Joven Aprendiz - Infraestructura de Sistemas (PCP)",
    exp2_period: "sep de 2023 – mar de 2025 · 1 año y 7 meses",
    exp2_location: "São Paulo, Brasil · Híbrida",
    exp2_desc: "Monitoreo, infraestructura y soporte en el Command Center (PCP B2C).",
    exp2_t1: "Monitoreo con <strong>Grafana, Dynatrace, Elastic, Kibana, Splunk y Zabbix</strong>.",
    exp2_t2: "Análisis de <strong>logs y métricas</strong> para diagnóstico de fallas.",
    exp2_t3: "Gestión de mallas de proceso en <strong>Control-M</strong>.",
    exp2_t4: "Gestión de accesos y reportes en <strong>SiTef Web</strong>.",
    exp2_t5: "Atención de incidentes via <strong>ServiceNow</strong>.",
    exp2_t6: "Ejecución de <strong>checklists operativos diarios</strong>.",
    exp2_t7: "Seguimiento de procesos de <strong>portabilidad en Linux</strong>.",
    exp2_t8: "Monitoreo de colas para <strong>São Paulo y otras regiones</strong>.",
    exp2_t9: "Validación de componentes <strong>Siebel</strong>.",
    exp2_t10: "Escalamiento de <strong>alertas operativas</strong>.",
    exp2_t11: "Análisis de causas de fallas operativas.",
    exp2_t12: "Mantenimiento de <strong>documentación y flujos</strong>.",
    exp2_t13: "Entrenamiento de nuevos integrantes del equipo.",
    exp2_t14: "Operación en <strong>entornos Linux</strong>.",
    exp2_t15: "Comunicación constante sobre el estado del entorno.",
    footer_rights: "© 2026 • Portafolio de Kauê Rodrigues Mirom • TI • São Paulo, Brasil"
  },
  fr: {
    doc_title: "Ma Carrière Sur Un Site Web !",
    nav_about: "À propos",
    nav_projects: "Projets",
    nav_contact: "Contact",
    nav_skills: "Compétences Techniques",
    nav_achievements: "Réalisations",
    nav_github: "Github",
    header_role: "Analyste Support Systèmes Jr",
    header_subtitle_text: "Spécialiste SRE & DevOps chez Vivo (Telefônica Brasil)",
    status_online: "SYSTEM ONLINE",
    core_title: "> Core & Méthodologies",
    obs_title: "> Observabilité & Surveillance",
    tag_monit: "Surveillance",
    auto_title: "> Automatisation & Continuous Delivery",
    tag_auto: "Automatisation",
    infra_title: "> Infrastructure & Base",
    tag_infra: "Infrastructure",
    download_cv: "Télécharger le CV !",
    about_title: "À propos de moi",
    about_p1: "Mon parcours en technologies de l'information a débuté par un diplôme technique en informatique chez Megatoc.",
    about_p2: "Au cours de près de <strong>3 ans d'expérience chez Vivo</strong>, j'ai débuté comme Apprenti au Command Center pour évoluer comme Stagiaire Systèmes dans l'équipe <strong>Emergency Response Team (ERT)</strong>.",
    about_p3: "J'ai travaillé dans des <strong>environnements de production critiques</strong> axés sobre l'observabilité, la résolution d'incidents, la gestion des problèmes et le <strong>Site Reliability Engineering (SRE)</strong>.",
    about_p4: "Mon approche combine <strong>développement logiciel, infrastructure et automatisation</strong>.",
    about_p5: "Actuellement, j'étudie le <strong>Génie Logiciel</strong> pour approfondir le Full-Stack, le Cloud, la sécurité et l'<strong>Intelligence Artificielle</strong>.",
    about_p6: "Mon objectif est d'évoluer à l'intersection du <strong>Software, SRE, Observabilité et Cloud</strong>.",
    edu_title: "Formation",
    edu_c1_inst: "Université Nove de Julho",
    edu_c1_title: "Diplôme Supérieur en Analyse et Développement de Systèmes",
    edu_c1_period: "janv. 2025 – août 2027",
    edu_c1_p1: "Formation axée sur l'<strong>analyse, le développement et la mise en œuvre de systèmes informatique</strong>.",
    edu_c1_p2: "Projets pratiques utilisant <strong>Java, Python et SQL</strong>.",
    edu_c1_p3: "Apprentissage des méthodes <strong>Scrum et Kanban</strong>.",
    edu_c1_p4: "Introduction à l'<strong>IA, au développement mobile et à la cybersécurité</strong>.",
    edu_skills_title: "Compétences clés :",
    edu_c1_k1: "Programmation et développement",
    edu_c1_k2: "Java, Python et SQL",
    edu_c1_k3: "Bases de données",
    edu_c1_k4: "Architecture logicielle",
    edu_c1_k5: "Scrum et Kanban",
    edu_c1_k6: "Résolution de problèmes",
    edu_c1_k7: "Gestion de projets logiciels",
    edu_c1_k8: "Intelligence Artificielle",
    edu_c1_k9: "Développement mobile",
    edu_c1_k10: "Sécurité de l'information",
    edu_c2_inst: "Cruzeiro do Sul Virtual",
    edu_c2_title: "Baccalauréat en Génie Logiciel",
    edu_c2_period: "janv. 2026 – déc. 2029",
    edu_c2_p1: "Maîtrise complète du <strong>cycle de vie du logiciel (SDLC)</strong>.",
    edu_c2_p2: "Architecture, Cloud, sécurité et IA.",
    edu_areas_title: "Domaines de connaissances :",
    edu_c2_k1: "<strong>Développement Full-Stack:</strong> Web et Mobile.",
    edu_c2_k2: "<strong>Données:</strong> bases de données et Data Science.",
    edu_c2_k3: "<strong>Cloud:</strong> architecture et scalabilité.",
    edu_c2_k4: "<strong>Qualité:</strong> tests logiciels et sécurité.",
    edu_c2_k5: "<strong>Gestion:</strong> méthodes agiles.",
    edu_c2_k6: "<strong>IA:</strong> Prompt Engineering et automatisation.",
    edu_c2_p3: "Création d'un <strong>outil automatisé de supervision WebLogic</strong>.",
    edu_c2_p4: "Transformation d'une vérification manuelle en processus automatique.",
    edu_kpi_title: "Résultat et Impact (KPI)",
    edu_kpi_val: "1 heure → 5 minutes",
    edu_kpi_desc: "Réduction de <strong>92% du temps d'inspection</strong>.",
    edu_skills_dev: "Compétences acquises :",
    edu_c2_s1: "UX/UI Design",
    edu_c2_s2: "Cloud Computing",
    edu_c2_s3: "Tests Logiciels",
    edu_c2_s4: "Architecture Systèmes",
    edu_c2_s5: "Développement Full-Stack",
    edu_c2_s6: "Automatisation",
    edu_c2_s7: "Qualité Logicielle",
    edu_c2_s8: "Sécurité Applicative",
    edu_c2_s9: "Intelligence Artificielle",
    edu_c2_s10: "Méthodes Agiles",
    courses_title: "Formations",
    courses_p1: "Cours suivis sur <strong>Alura</strong>, <strong>LinkedIn Learning</strong>, <strong>Vivo</strong>, etc.",
    courses_topics_title: "Sujets étudies :",
    courses_t1: "<strong>Programmation:</strong> Java, JS, Git, GitHub.",
    courses_t2: "<strong>DevOps:</strong> Linux, Docker, Zabbix, Elastic, ServiceNow.",
    courses_t3: "<strong>Containers:</strong> Kubernetes.",
    courses_t4: "<strong>Bases de données:</strong> SQL.",
    courses_t5: "<strong>Soft Skills:</strong> Scrum, communication.",
    courses_t6: "<strong>Réseaux & IT:</strong> Systèmes d'exploitation et SDLC.",
    courses_p2: "Engagement continu dans l'apprentissage.",
    exp_title: "Expérience",
    exp1_role: "Stagiaire Systèmes - Observabilité & ERT (SRE)",
    exp1_period: "mars 2025 – présent · 1 an 7 mois",
    exp1_location: "São Paulo, Brésil · Hybride",
    exp1_desc: "Support à la fiabilité des environnements B2C au sein de l'ERT.",
    exp1_t1: "Dashboards et alertes avec ServiceNow, Elastic, Zabbix.",
    exp1_t2: "Analyse de <strong>logs et métriques</strong>.",
    exp1_t3: "Gestion d'incidents critiques.",
    exp1_t4: "Analyse des causes racines (RCA).",
    exp1_t5: "Suivi des PRBs (Problem Records).",
    exp1_t6: "Workflows pour alertes critiques.",
    exp1_t7: "Développement HTML/CSS/JS.",
    exp1_t8: "Création d'un Health Check automatisé.",
    exp1_t9: "Outils de suivi WebLogic.",
    exp1_t10: "Oracle Server et Jenkins.",
    exp1_t11: "Maintenance et validation en production.",
    exp1_t12: "SharePoint pour la gestion de projet.",
    exp1_t13: "Outils web inter-équipes.",
    exp1_t14: "Formations sur la qualité des PRBs.",
    exp1_t15: "Optimisation de processus opérationnels.",
    exp2_role: "Jeune Apprenti - Infrastructure (PCP)",
    exp2_period: "sept. 2023 – mars 2025 · 1 an 7 mois",
    exp2_location: "São Paulo, Brésil · Hybride",
    exp2_desc: "Command Center B2C : surveillance et support d'infrastructure.",
    exp2_t1: "Monitoring Grafana, Dynatrace, Elastic, Splunk, Zabbix.",
    exp2_t2: "Diagnostic d'incidents via logs.",
    exp2_t3: "Gestion des tâches Control-M.",
    exp2_t4: "Rapports SiTef Web.",
    exp2_t5: "Gestion de tickets ServiceNow.",
    exp2_t6: "Checklists quotidiennes.",
    exp2_t7: "Suivi des processus de portabilité Linux.",
    exp2_t8: "Supervision des files d'attente.",
    exp2_t9: "Validation des nœuds Siebel.",
    exp2_t10: "Escalade d'alertes.",
    exp2_t11: "Analyse des pannes.",
    exp2_t12: "Rédaction de documentations.",
    exp2_t13: "Formation des nouveaux apprentis.",
    exp2_t14: "Commandes sur environnements Linux.",
    exp2_t15: "Rapports d'état opérationnel.",
    footer_rights: "© 2026 • Portfolio de Kauê Rodrigues Mirom • IT • São Paulo, Brésil"
  },
  it: {
    doc_title: "La Mia Carriera In Un Sito!",
    nav_about: "Chi sono",
    nav_projects: "Progetti",
    nav_contact: "Contatti",
    nav_skills: "Competenze Tecniche",
    nav_achievements: "Traguardi",
    nav_github: "Github",
    header_role: "Analista di Supporto Sistemi Jr",
    header_subtitle_text: "Specialista SRE & DevOps presso Vivo (Telefônica Brasil)",
    status_online: "SYSTEM ONLINE",
    core_title: "> Core & Metodologie",
    obs_title: "> Osservabilità & Monitoraggio",
    tag_monit: "Monitoraggio",
    auto_title: "> Automazione & Continuous Delivery",
    tag_auto: "Automazione",
    infra_title: "> Infrastruttura & Base",
    tag_infra: "Infrastruttura",
    download_cv: "Scarica il CV!",
    about_title: "Chi sono",
    about_p1: "Il mio percorso nel mondo IT è iniziato con la formazione tecnica presso Megatoc.",
    about_p2: "Con circa <strong>3 anni di esperienza in Vivo</strong>, ho iniziato come Giovane Apprendista fino a diventare Stagista nell'<strong>Emergency Response Team (ERT)</strong>.",
    about_p3: "Ho lavorato in <strong>ambienti critici di produzione</strong> focalizzandomi su osservabilità, analisi dei log e pratiche <strong>Site Reliability Engineering (SRE)</strong>.",
    about_p4: "Combino sviluppo software, infrastruttura e automazione.",
    about_p5: "Attualmente studio <strong>Ingegneria del Software</strong> approfondendo Full-Stack, Cloud, Sicurezza e <strong>Intelligenza Artificiale</strong>.",
    about_p6: "Punto a crescere all'intersezione tra <strong>Software, SRE, Osservabilità e Cloud</strong>.",
    edu_title: "Formazione",
    edu_c1_inst: "Università Nove de Julho",
    edu_c1_title: "Laurea Breve in Analisi e Sviluppo di Sistemi",
    edu_c1_period: "gen 2025 – ago 2027",
    edu_c1_p1: "Formazione incentrata su <strong>analisi, sviluppo e implementazione di sistemi</strong>.",
    edu_c1_p2: "Progetti pratici in <strong>Java, Python e SQL</strong>.",
    edu_c1_p3: "Competenze in <strong>Scrum e Kanban</strong>.",
    edu_c1_p4: "Esposizione a <strong>Intelligenza Artificiale, sviluppo mobile e sicurezza</strong>.",
    edu_skills_title: "Competenze chiave:",
    edu_c1_k1: "Programmazione e sviluppo",
    edu_c1_k2: "Java, Python e SQL",
    edu_c1_k3: "Database",
    edu_c1_k4: "Architettura software",
    edu_c1_k5: "Scrum e Kanban",
    edu_c1_k6: "Risoluzione dei problemi",
    edu_c1_k7: "Sviluppo di progetti software",
    edu_c1_k8: "Intelligenza Artificiale",
    edu_c1_k9: "Sviluppo Mobile",
    edu_c1_k10: "Sicurezza delle informazioni",
    edu_c2_inst: "Cruzeiro do Sul Virtual",
    edu_c2_title: "Laurea in Ingegneria del Software",
    edu_c2_period: "gen 2026 – dic 2029",
    edu_c2_p1: "Approfondimento del ciclo di vita del software (SDLC).",
    edu_c2_p2: "Focus su Cloud, Full-Stack, Sicurezza e IA.",
    edu_areas_title: "Aree di conoscenza:",
    edu_c2_k1: "<strong>Sviluppo Full-Stack:</strong> Web e Mobile.",
    edu_c2_k2: "<strong>Dati:</strong> modellazione e Data Science.",
    edu_c2_k3: "<strong>Cloud:</strong> architetture scalabili.",
    edu_c2_k4: "<strong>Qualità:</strong> testing e sicurezza.",
    edu_c2_k5: "<strong>Metodologie:</strong> sviluppo agile.",
    edu_c2_k6: "<strong>Intelligenza Artificiale:</strong> Prompt Engineering.",
    edu_c2_p3: "Sviluppato un <strong>sistema automatico di controllo dei server WebLogic</strong>.",
    edu_c2_p4: "Ottimizzazione dei tempi di controllo da manuale ad automatico.",
    edu_kpi_title: "Risultato e Impatto (KPI)",
    edu_kpi_val: "1 ora → 5 minuti",
    edu_kpi_desc: "Riduzione del <strong>92% del tempo di ispezione</strong>.",
    edu_skills_dev: "Competenze sviluppate:",
    edu_c2_s1: "UX/UI Design",
    edu_c2_s2: "Cloud Computing",
    edu_c2_s3: "Testing Software",
    edu_c2_s4: "Pianificazione Sistemi",
    edu_c2_s5: "Sviluppo Front-End e Back-End",
    edu_c2_s6: "Automazione",
    edu_c2_s7: "Qualità del Software",
    edu_c2_s8: "Sicurezza Applicativa",
    edu_c2_s9: "Intelligenza Artificiale",
    edu_c2_s10: "Metodologie Agili",
    courses_title: "Corsi",
    courses_p1: "Corsi completati su piattaforme come <strong>Alura</strong>, <strong>LinkedIn Learning</strong> e <strong>Vivo</strong>.",
    courses_topics_title: "Argomenti principali:",
    courses_t1: "<strong>Programmazione:</strong> Java, JS, Git, GitHub.",
    courses_t2: "<strong>DevOps:</strong> Linux, Docker, Zabbix, Elastic, ServiceNow.",
    courses_t3: "<strong>Orchestrazione:</strong> Kubernetes.",
    courses_t4: "<strong>Database:</strong> SQL.",
    courses_t5: "<strong>Soft Skills:</strong> Agile, Scrum, comunicazione.",
    courses_t6: "<strong>Fondamenti IT:</strong> Reti mobili, sistemi operativi.",
    courses_p2: "Apprendimento continuo e aggiornamento costante.",
    exp_title: "Esperienza",
    exp1_role: "Stagista Sistemi - Osservabilità & ERT (SRE)",
    exp1_period: "mar 2025 – presente · 1 Anno e 7 Mesi",
    exp1_location: "San Paolo, Brasile · Ibrido",
    exp1_desc: "Operatività nell'ERT B2C per la gestione dell'affidabilità e automazione.",
    exp1_t1: "Creazione dashboard con ServiceNow, Elastic e Zabbix.",
    exp1_t2: "Analisi di <strong>metriche e log</strong>.",
    exp1_t3: "Gestione degli incidenti critici.",
    exp1_t4: "Analisi Root Cause Analysis (RCA).",
    exp1_t5: "Gestione dei PRB (Problem Records).",
    exp1_t6: "Flussi di lavoro per avvisi critici.",
    exp1_t7: "Sviluppo Web con HTML, CSS, JavaScript.",
    exp1_t8: "Creazione di Health Check automatici.",
    exp1_t9: "Sistemi di monitoraggio WebLogic.",
    exp1_t10: "Gestione con Oracle Server e Jenkins.",
    exp1_t11: "Attività di Stop/Start e analisi log.",
    exp1_t12: "Creazione SharePoint aziendale.",
    exp1_t13: "Sviluppo di pagine di integrazione per PO.",
    exp1_t14: "Formazione interna sulla qualità PRB.",
    exp1_t15: "Automazione dei processi operativi.",
    exp2_role: "Giovane Apprendista - Infrastruttura (PCP)",
    exp2_period: "set 2023 – mar 2025 · 1 anno e 7 mesi",
    exp2_location: "San Paolo, Brasile · Ibrido",
    exp2_desc: "Supporto operativo presso il Command Center B2C.",
    exp2_t1: "Monitoraggio con Grafana, Dynatrace, Elastic, Splunk, Zabbix.",
    exp2_t2: "Analisi guasti tramite log.",
    exp2_t3: "Gestione batch su Control-M.",
    exp2_t4: "Estrazione report su SiTef Web.",
    exp2_t5: "Gestione ticket ServiceNow.",
    exp2_t6: "Esecuzione checklist quotidiane.",
    exp2_t7: "Controllo processi di portabilità Linux.",
    exp2_t8: "Supervisione delle code di elaborazione.",
    exp2_t9: "Controllo componenti Siebel.",
    exp2_t10: "Gestione avvisi operativi.",
    exp2_t11: "Risoluzione problemi su infrastruttura.",
    exp2_t12: "Creazione documentazione tecnica.",
    exp2_t13: "Formazione dei nuovi apprendisti.",
    exp2_t14: "Operatività in ambiente Linux.",
    exp2_t15: "Comunicazione continua sullo stato del sistema.",
    footer_rights: "© 2026 • Portfolio di Kauê Rodrigues Mirom • IT • San Paolo, Brasile"
  }
};

/**
 * Idioma inicial carregado a partir do localStorage ou 'pt'
 */
let currentLang = localStorage.getItem('preferred_lang') || 'pt';

/**
 * Atualiza todas as strings da aplicação de acordo com o idioma
 */
function setLanguage(lang) {
  if (!translations[lang]) {
    lang = 'pt';
  }

  currentLang = lang;
  localStorage.setItem('preferred_lang', lang);
  document.documentElement.lang = lang === 'pt' ? 'pt-br' : lang;

  // Atualiza título do documento
  if (translations[lang].doc_title) {
    document.title = translations[lang].doc_title;
  }

  // Atualiza elementos com o atributo data-i18n
  const elements = document.querySelectorAll('[data-i18n]');
  elements.forEach((element) => {
    const key = element.getAttribute('data-i18n');
    const translation = translations[lang][key];

    if (translation !== undefined) {
      element.innerHTML = translation;
    }
  });

  // Atualiza a interface do botão de idiomas
  updateLanguageUI(lang);
}

/**
 * Atualiza a bandeira e texto do botão seletor
 */
function updateLanguageUI(activeLang) {
  const flags = {
    pt: 'fi-br',
    en: 'fi-us',
    es: 'fi-es',
    fr: 'fi-fr',
    it: 'fi-it'
  };

  const btnFlag = document.getElementById('btnFlag');
  const btnLang = document.getElementById('btnLang');

  if (btnFlag) {
    btnFlag.className = `fi ${flags[activeLang] || 'fi-br'}`;
  }
  if (btnLang) {
    btnLang.textContent = activeLang.toUpperCase();
  }
}

/**
 * Troca de idioma disparada pelas opções do dropdown
 */
function changeLanguage(lang) {
  setLanguage(lang);
  closeLangDropdown();
}

/**
 * Controla a visibilidade do menu suspenso de idiomas
 */
function toggleLangMenu() {
  const dropdown = document.getElementById('langDropdown');
  if (dropdown) {
    const isVisible = dropdown.style.display === 'block';
    dropdown.style.display = isVisible ? 'none' : 'block';
  }
}

function closeLangDropdown() {
  const dropdown = document.getElementById('langDropdown');
  if (dropdown) {
    dropdown.style.display = 'none';
  }
}

/**
 * Eventos executados após o carregamento do DOM
 */
document.addEventListener('DOMContentLoaded', () => {
  // Executa a tradução inicial
  setLanguage(currentLang);

  // Fecha o dropdown ao clicar fora
  document.addEventListener('click', (event) => {
    const langContainer = document.querySelector('.lang-selector');
    if (langContainer && !langContainer.contains(event.target)) {
      closeLangDropdown();
    }
  });
});
