/**
 * Dicionário de Traduções do Portfólio
 */
const translations = {
  pt: {
    doc_title: "Minha Carreira Em Um Site!",
    nav_about: "Sobre mim",
    nav_projects: "Projetos",
    nav_contact: "Contato",
    nav_skills: "Habilidades Técnicas",
    nav_achievements: "Conquistas",
    nav_github: "Github",
    header_role: "Analista de Suporte a Sistemas Jr",
    header_subtitle_text: "Especialista em <strong style=\"color: #00ff88; font-weight: 700;\">SRE & DevOps</strong> na <span style=\"color: #ffffff; font-weight: 700; border-bottom: 2px solid #00ff88; padding-bottom: 2px;\">Vivo (Telefônica Brasil)</span>",
    status_online: "SYSTEM ONLINE",
    core_title: "> Core & Metodologias",
    obs_title: "> Observabilidade & Monitoramento",
    tag_monit: "Monitoramento",
    auto_title: "> Automação & Continuous Delivery",
    tag_auto: "Automação",
    infra_title: "> Infraestrutura & Base",
    tag_infra: "Infraestrutura",
    download_cv: "Baixar Currículo!",
    about_title: "Sobre mim",
    about_p1: "Minha trajetória na área de Tecnologia da Informação começou com minha formação técnica em Informática e Tecnologia da Informação pela Megatoc, onde construí minha base em desenvolvimento, infraestrutura, sistemas e suporte tecnológico.",
    about_p2: "Ao longo de aproximadamente <strong>3 anos de experiência na Vivo (Telefônica Brasil)</strong>, iniciei minha carreira como Jovem Aprendiz em Infraestrutura de Sistemas, no Command Center (Equipe de Produção - B2C), evoluindo posteriormente para Estagiário de Sistemas na Gerência de Observabilidade, com atuação junto ao <strong>Emergency Response Team (ERT)</strong>.",
    about_p3: "Durante essa jornada, atuei em <strong>ambientes críticos de produção</strong>, desenvolvendo experiência em observabilidade, monitoramento, resposta a incidentes, análise de logs, gestão de problemas, automação e práticas de <strong>Site Reliability Engineering (SRE)</strong>.",
    about_p4: "Minha atuação combina conhecimentos de <strong>desenvolvimento de software, infraestrutura, observabilidade e automação</strong>, buscando transformar processos operacionais em soluções mais eficientes, confiáveis e escaláveis.",
    about_p5: "Atualmente, direciono minha formação para <strong>Engenharia de Software</strong>, aprofundando conhecimentos em desenvolvimento Full-Stack, arquitetura de sistemas, Cloud, bancos de dados, segurança, metodologias ágeis e <strong>Inteligência Artificial</strong>.",
    about_p6: "Tenho como objetivo continuar evoluindo profissionalmente na interseção entre <strong>Software, SRE, Observabilidade, Automação e Cloud</strong>, utilizando tecnologia para resolver problemas reais, otimizar processos e aumentar a confiabilidade dos ambientes e sistemas.",
    edu_title: "Formação",
    edu_c1_inst: "Universidade Nove de Julho",
    edu_c1_title: "Tecnólogo em Análise e Desenvolvimento de Sistemas",
    edu_c1_period: "jan de 2025 – ago de 2027",
    edu_c1_p1: "Formação voltada à <strong>análise, desenvolvimento e implementação de sistemas computacionais</strong>, proporcionando uma base sólida em programação, engenharia de software, modelagem de dados, arquitetura de sistemas e desenvolvimento de soluções.",
    edu_c1_p2: "Ao longo da graduação, desenvolvi projetos acadêmicos e práticos utilizando tecnologias como <strong>Java, Python e SQL</strong>, trabalhando desde a análise e planejamento até o desenvolvimento e validação de aplicações.",
    edu_c1_p3: "Também desenvolvi conhecimentos em <strong>Scrum e Kanban</strong>, aplicados à organização e gestão de projetos, além de práticas de desenvolvimento, resolução de problemas e trabalho colaborativo.",
    edu_c1_p4: "A formação também proporcionou contato com temas como <strong>Inteligência Artificial, desenvolvimento mobile e segurança da informação</strong>, ampliando minha visão sobre diferentes áreas do ecossistema de tecnologia.",
    edu_skills_title: "Principais competências:",
    edu_c1_k1: "Programação e desenvolvimento de sistemas",
    edu_c1_k2: "Java, Python e SQL",
    edu_c1_k3: "Modelagem e desenvolvimento de bancos de dados",
    edu_c1_k4: "Engenharia e arquitetura de software",
    edu_c1_k5: "Scrum e Kanban",
    edu_c1_k6: "Resolução e otimização de problemas computacionais",
    edu_c1_k7: "Desenvolvimento de projetos de software",
    edu_c1_k8: "Inteligência Artificial e novas tecnologias",
    edu_c1_k9: "Desenvolvimento mobile",
    edu_c1_k10: "Segurança da informação",
    edu_c2_inst: "Cruzeiro do Sul Virtual",
    edu_c2_title: "Bacharelado em Engenharia de Software",
    edu_c2_period: "jan de 2026 – dez de 2029",
    edu_c2_p1: "Minha formação em <strong>Engenharia de Software</strong> tem como objetivo aprofundar conhecimentos técnicos e desenvolver uma visão completa sobre o <strong>ciclo de vida do desenvolvimento de software (SDLC)</strong>, desde a concepção e arquitetura até desenvolvimento, testes, segurança e evolução de sistemas.",
    edu_c2_p2: "A formação aborda conceitos de <strong>arquitetura de sistemas escaláveis, desenvolvimento Full-Stack, Cloud Computing, bancos de dados, qualidade de software, segurança, metodologias ágeis e Inteligência Artificial</strong>.",
    edu_areas_title: "Principais áreas de conhecimento:",
    edu_c2_k1: "<strong>Desenvolvimento Full-Stack:</strong> desenvolvimento de aplicações Web e Mobile, abrangendo Front-End, Back-End, arquitetura de aplicações e boas práticas de desenvolvimento.",
    edu_c2_k2: "<strong>Dados e Sistemas de Informação:</strong> modelagem de dados, bancos de dados, Ciência de Dados e desenvolvimento de Sistemas de Informação.",
    edu_c2_k3: "<strong>Arquitetura e Cloud:</strong> fundamentos de computação em nuvem, escalabilidade, disponibilidade, arquitetura de sistemas e desenvolvimento de aplicações resilientes.",
    edu_c2_k4: "<strong>Qualidade e Segurança:</strong> testes de software, qualidade, segurança em ambientes digitais, integridade, performance e confiabilidade.",
    edu_c2_k5: "<strong>Metodologias e Gestão:</strong> aplicação de metodologias ágeis e conceitos de gestão de projetos, incluindo Scrum e Kanban.",
    edu_c2_k6: "<strong>Inteligência Artificial:</strong> Engenharia de Prompt e aplicações de IA voltadas ao desenvolvimento, automação e otimização de processos.",
    edu_c2_p3: "Durante a formação, desenvolvi uma <strong>ferramenta de automação para monitoramento da saúde e disponibilidade de ambientes de produção</strong>, com foco em servidores WebLogic e filas de processamento.",
    edu_c2_p4: "O projeto transformou um processo de inspeção manual em uma rotina automatizada, proporcionando uma redução significativa no tempo necessário para a execução do procedimento.",
    edu_kpi_title: "Resultado e Impacto (KPI)",
    edu_kpi_val: "1 hora → 5 minutos",
    edu_kpi_desc: "Redução de aproximadamente <strong>92% no tempo de inspeção</strong> por meio da execução automatizada.",
    edu_skills_dev: "Competências desenvolvidas:",
    edu_c2_s1: "Design de Interfaces (UX/UI)",
    edu_c2_s2: "Computação em Nuvem",
    edu_c2_s3: "Testes de Software — Unitários e Funcionais",
    edu_c2_s4: "Planejamento e Arquitetura de Sistemas",
    edu_c2_s5: "Desenvolvimento Front-End e Back-End",
    edu_c2_s6: "Automação de Sistemas",
    edu_c2_s7: "Qualidade de Software",
    edu_c2_s8: "Segurança de Aplicações",
    edu_c2_s9: "Inteligência Artificial",
    edu_c2_s10: "Metodologias Ágeis",
    courses_title: "Cursos",
    courses_p1: "Ao longo da minha trajetória, busquei constantemente aprimorar meus conhecimentos técnicos e comportamentais por meio de formações complementares. Concluí diversos cursos em plataformas reconhecidas como <strong>Alura</strong>, <strong>Fundação Bradesco</strong>, <strong>LinkedIn Learning</strong>, <strong>Enabley UK & ROI</strong>, <strong>Vivae</strong> e também pela <strong>Vivo (Telefônica Brasil)</strong>, abrangendo áreas essenciais da tecnologia e do desenvolvimento profissional.",
    courses_topics_title: "Entre os principais temas estudados estão:",
    courses_t1: "<strong>Programação e Desenvolvimento:</strong> lógica com JavaScript, desenvolvimento back-end em Java, fundamentos de POO, criação de jogos, Git e GitHub, API e integração contínua.",
    courses_t2: "<strong>Infraestrutura e DevOps:</strong> PowerShell, Docker, Linux (terminal, processos, permissões, CLI), Windows Prompt, redes, ServiceNow, Zabbix, Elastic e Datadog.",
    courses_t3: "<strong>Orquestração e Contêineres:</strong> Kubernetes (Pods, Services, ConfigMaps, Deployments e Escalabilidade).",
    courses_t4: "<strong>Banco de Dados:</strong> fundamentos de SQL e gestão de dados.",
    courses_t5: "<strong>Metodologias Ágeis e Soft Skills:</strong> Scrum/Kanban, postura profissional, controle de impulso, habilidades comportamentais e diversidade.",
    courses_t6: "<strong>Fundamentos de TI:</strong> sistemas operacionais, engenharia de redes móveis, SDLC (ciclo de vida do desenvolvimento de software), diferenças entre front-end e back-end e carreira de programador.",
    courses_p2: "Esses cursos reforçam meu compromisso com a aprendizagem contínua e me proporcionam uma base sólida para atuar com eficiência em projetos de tecnologia, infraestrutura e desenvolvimento de software.",
    exp_title: "Experiência",
    exp1_role: "Estagiário de Sistema - Observabilidade & ERT (SRE)",
    exp1_period: "mar de 2025 – o momento · 1 Ano e 7 Meses",
    exp1_location: "São Paulo, Brasil · Híbrida",
    exp1_desc: "Atuação como Estagiário de Sistemas na Gerência de Observabilidade, integrando a equipe de Respostas Emergenciais B2C (ERT). Experiência direcionada à confiabilidade de ambientes críticos, observabilidade, automação, análise de incidentes e melhoria contínua dos processos operacionais.",
    exp1_t1: "Desenvolvimento e evolução de <strong>alarmes e dashboards</strong> utilizando ServiceNow, Elastic e Zabbix.",
    exp1_t2: "Monitoramento de ambientes críticos e análise de <strong>métricas, eventos e logs</strong> para identificação e diagnóstico de falhas.",
    exp1_t3: "Participação na <strong>resposta a incidentes críticos B2C</strong>, apoiando as etapas de investigação, diagnóstico e resolução.",
    exp1_t4: "Realização de <strong>análises de causa raiz (RCA)</strong> para investigação de falhas e problemas recorrentes.",
    exp1_t5: "Atuação na gestão e evolução de <strong>PRBs (Problem Records)</strong>, contribuindo para a identificação e tratamento de causas recorrentes.",
    exp1_t6: "Desenvolvimento de <strong>workflows para alertas de problemas críticos</strong>, contribuindo para maior agilidade e eficiência operacional.",
    exp1_t7: "Desenvolvimento de automações e aplicações web utilizando <strong>HTML, CSS e JavaScript</strong>.",
    exp1_t8: "Desenvolvimento de um <strong>Health Check automatizado</strong> para validação da saúde e disponibilidade dos servidores.",
    exp1_t9: "Desenvolvimento de soluções para acompanhamento de <strong>servidores WebLogic e filas de processamento</strong>.",
    exp1_t10: "Administração operacional de ambientes utilizando <strong>Oracle Server e Jenkins</strong>.",
    exp1_t11: "Execução de procedimentos de <strong>Stop/Start, limpeza de cache, análise de logs e validação de componentes</strong> em ambientes de produção.",
    exp1_t12: "Criação de <strong>SharePoint para gestão de projetos em produção e treinamento de colaboradores</strong>.",
    exp1_t13: "Desenvolvimento de páginas e ferramentas web para facilitar a integração entre equipes de <strong>Projetos, Operações e Product Owners</strong>.",
    exp1_t14: "Atuação como referência na <strong>qualidade de PRBs</strong>, realizando análises, feedbacks e treinamentos para aprimorar a padronização e maturidade da Gestão de Problemas.",
    exp1_t15: "Desenvolvimento de soluções voltadas à <strong>automação e otimização de processos operacionais</strong>, reduzindo atividades manuais e aumentando a eficiência da equipe.",
    exp2_role: "Jovem Aprendiz - Infraestrutura de Sistemas (PCP)",
    exp2_period: "set de 2023 – mar de 2025 · 1 ano e 7 meses",
    exp2_location: "São Paulo, Brasil · Híbrida",
    exp2_desc: "Minha primeira experiência profissional em Tecnologia foi na Vivo, atuando na área de Infraestrutura de Sistemas, no Command Center (PCP B2C). Nesse período, desenvolvi uma base sólida em monitoramento, observabilidade, infraestrutura, análise de incidentes e suporte à operação de ambientes críticos.",
    exp2_t1: "Monitoramento de ambientes B2C utilizando <strong>Grafana, Dynatrace, Elastic, Kibana, Splunk e Zabbix</strong>.",
    exp2_t2: "Análise de <strong>métricas, eventos e logs</strong> para identificação e diagnóstico de falhas.",
    exp2_t3: "Gerenciamento e acompanhamento de <strong>jobs e malhas de processamento no Control-M</strong>.",
    exp2_t4: "Extração de relatórios e gerenciamento de acessos utilizando <strong>SiTef Web</strong>.",
    exp2_t5: "Tratamento e acompanhamento de solicitações e incidentes através do <strong>ServiceNow</strong>.",
    exp2_t6: "Execução de <strong>checklists operacionais diários</strong> para validação da saúde dos ambientes.",
    exp2_t7: "Monitoramento dos processos de <strong>Recovery da Portabilidade em ambientes Linux</strong>, acompanhando logs e filas de processamento.",
    exp2_t8: "Acompanhamento do processamento das filas referentes aos ambientes de <strong>São Paulo e demais regiões do Brasil</strong>.",
    exp2_t9: "Validação de <strong>componentes e nodes do Siebel</strong>, contribuindo para a estabilidade e disponibilidade do sistema.",
    exp2_t10: "Comunicação e escalonamento de <strong>alertas operacionais</strong> para as equipes responsáveis.",
    exp2_t11: "Análise e tratamento de problemas, utilizando informações de <strong>logs e indicadores</strong> para apoiar a identificação da causa raiz.",
    exp2_t12: "Criação e manutenção de <strong>documentações, automações e fluxos operacionais</strong>.",
    exp2_t13: "Apoio na integração e <strong>treinamento de novos colaboradores</strong>, compartilhando conhecimentos sobre sistemas internos e processos de monitoramento.",
    exp2_t14: "Acesso e operação de <strong>ambientes Linux</strong> para análise de logs e acompanhamento de processos de recuperação.",
    exp2_t15: "Acompanhamento da saúde dos ambientes e comunicação de ocorrências para suporte à continuidade da operação.",
    footer_rights: "© 2026 • Portfólio de Kauê Rodrigues Mirom • TI • São Paulo, Brasil",
    lang_btn_title: "Mudar Idioma",
    back_to_top: "Voltar ao topo"
  },
  en: {
    doc_title: "My Career On A Website!",
    nav_about: "About me",
    nav_projects: "Projects",
    nav_contact: "Contact",
    nav_skills: "Technical Skills",
    nav_achievements: "Achievements",
    nav_github: "Github",
    header_role: "Jr Systems Support Analyst",
    header_subtitle_text: "Specialist in <strong style=\"color: #00ff88; font-weight: 700;\">SRE & DevOps</strong> at <span style=\"color: #ffffff; font-weight: 700; border-bottom: 2px solid #00ff88; padding-bottom: 2px;\">Vivo (Telefônica Brasil)</span>",
    status_online: "SYSTEM ONLINE",
    core_title: "> Core & Methodologies",
    obs_title: "> Observability & Monitoring",
    tag_monit: "Monitoring",
    auto_title: "> Automation & Continuous Delivery",
    tag_auto: "Automation",
    infra_title: "> Infrastructure & Base",
    tag_infra: "Infrastructure",
    download_cv: "Download Resume!",
    about_title: "About me",
    about_p1: "My trajectory in Information Technology began with technical education in IT at Megatoc, where I built my foundation in development, infrastructure, systems, and tech support.",
    about_p2: "Over approximately <strong>3 years of experience at Vivo (Telefônica Brasil)</strong>, I started as a Young Apprentice in Systems Infrastructure at the Command Center (B2C Production), later evolving to Systems Intern in Observability Management with the <strong>Emergency Response Team (ERT)</strong>.",
    about_p3: "During this journey, I worked in <strong>mission-critical production environments</strong>, gaining hands-on experience in observability, monitoring, incident response, log analysis, problem management, automation, and <strong>Site Reliability Engineering (SRE)</strong> practices.",
    about_p4: "My work combines knowledge in <strong>software development, infrastructure, observability, and automation</strong>, aiming to transform operational workflows into efficient, reliable, and scalable solutions.",
    about_p5: "Currently, I direct my academic studies toward <strong>Software Engineering</strong>, deepening expertise in Full-Stack development, system architecture, Cloud, databases, security, agile methodologies, and <strong>Artificial Intelligence</strong>.",
    about_p6: "My goal is to continuously evolve at the intersection of <strong>Software, SRE, Observability, Automation, and Cloud</strong>, applying technology to solve real-world problems and enhance system reliability.",
    edu_title: "Education",
    edu_c1_inst: "Nove de Julho University",
    edu_c1_title: "Associate Degree in Systems Analysis and Development",
    edu_c1_period: "Jan 2025 – Aug 2027",
    edu_c1_p1: "Degree focused on <strong>systems analysis, software development, and implementation</strong>, providing a solid grounding in programming, software engineering, database modeling, and solution design.",
    edu_c1_p2: "Throughout the degree, I developed academic and practical projects using technologies like <strong>Java, Python, and SQL</strong>, from initial requirement analysis to final deployment.",
    edu_c1_p3: "I also gained applied knowledge in <strong>Scrum and Kanban</strong> methodologies for project organization and execution.",
    edu_c1_p4: "The course introduced advanced topics in <strong>Artificial Intelligence, mobile development, and information security</strong>.",
    edu_skills_title: "Key Competencies:",
    edu_c1_k1: "Systems programming and software development",
    edu_c1_k2: "Java, Python, and SQL",
    edu_c1_k3: "Database design and development",
    edu_c1_k4: "Software engineering and architecture",
    edu_c1_k5: "Scrum and Kanban agile frameworks",
    edu_c1_k6: "Computational problem-solving and optimization",
    edu_c1_k7: "Software project execution",
    edu_c1_k8: "Artificial Intelligence and emerging tech",
    edu_c1_k9: "Mobile applications development",
    edu_c1_k10: "Information security fundamentals",
    edu_c2_inst: "Cruzeiro do Sul Virtual",
    edu_c2_title: "Bachelor's Degree in Software Engineering",
    edu_c2_period: "Jan 2026 – Dec 2029",
    edu_c2_p1: "My degree in <strong>Software Engineering</strong> aims to deepen technical expertise and master the entire <strong>Software Development Life Cycle (SDLC)</strong>, from system architecture to testing, deployment, and security.",
    edu_c2_p2: "The program covers <strong>scalable architecture, Full-Stack engineering, Cloud Computing, databases, software quality, security, and AI integrations</strong>.",
    edu_areas_title: "Core Knowledge Areas:",
    edu_c2_k1: "<strong>Full-Stack Development:</strong> Web and Mobile application engineering, covering Front-End, Back-End, and design patterns.",
    edu_c2_k2: "<strong>Data & Information Systems:</strong> Database modeling, SQL/NoSQL architectures, Data Science basics.",
    edu_c2_k3: "<strong>Cloud & Architecture:</strong> Cloud computing concepts, scalability, high availability, and resilient systems design.",
    edu_c2_k4: "<strong>Quality & Security:</strong> Unit testing, functional testing, cybersecurity fundamentals, and application performance.",
    edu_c2_k5: "<strong>Methodologies & Management:</strong> Agile frameworks application including Scrum and Kanban.",
    edu_c2_k6: "<strong>Artificial Intelligence:</strong> Prompt engineering and AI implementation in automation workflows.",
    edu_c2_p3: "During my studies, I engineered an <strong>automation tool to monitor production environment availability</strong>, focusing on WebLogic servers and processing queues.",
    edu_c2_p4: "This initiative converted manual inspections into an automated background routine, drastically lowering processing time.",
    edu_kpi_title: "Result & Impact (KPI)",
    edu_kpi_val: "1 hour → 5 minutes",
    edu_kpi_desc: "Achieved an approximate <strong>92% reduction in inspection time</strong> via automated scripts.",
    edu_skills_dev: "Skills Developed:",
    edu_c2_s1: "UX/UI Interface Design",
    edu_c2_s2: "Cloud Computing Fundamentals",
    edu_c2_s3: "Unit and Functional Testing",
    edu_c2_s4: "Systems Planning and Architecture",
    edu_c2_s5: "Front-End & Back-End Engineering",
    edu_c2_s6: "Systems Automation",
    edu_c2_s7: "Software Quality Assurance",
    edu_c2_s8: "Application Security Best Practices",
    edu_c2_s9: "Artificial Intelligence Solutions",
    edu_c2_s10: "Agile Project Execution",
    courses_title: "Courses & Certifications",
    courses_p1: "Throughout my growth, I continuously pursued learning via platforms like <strong>Alura</strong>, <strong>Fundação Bradesco</strong>, <strong>LinkedIn Learning</strong>, <strong>Enabley UK & ROI</strong>, <strong>Vivae</strong>, and internal programs at <strong>Vivo (Telefônica Brasil)</strong>.",
    courses_topics_title: "Main Focus Areas Included:",
    courses_t1: "<strong>Programming & Development:</strong> JavaScript logic, Java back-end development, OOP principles, Git & GitHub, REST APIs, and CI/CD.",
    courses_t2: "<strong>Infrastructure & DevOps:</strong> PowerShell, Docker, Linux administration, Networking, ServiceNow, Zabbix, Elastic Stack, and Datadog.",
    courses_t3: "<strong>Container Orchestration:</strong> Kubernetes (Pods, Deployments, ConfigMaps, and Scaling).",
    courses_t4: "<strong>Databases:</strong> SQL fundamentals and data administration.",
    courses_t5: "<strong>Agile & Soft Skills:</strong> Scrum/Kanban, leadership, emotional control, and workplace diversity.",
    courses_t6: "<strong>IT Foundations:</strong> Operating systems, telecom networks, SDLC models, and developer career tracks.",
    courses_p2: "These courses reinforce my commitment to continuous improvement and technical excellence.",
    exp_title: "Experience",
    exp1_role: "Systems Intern - Observability & ERT (SRE)",
    exp1_period: "Mar 2025 – Present · 1 yr 7 mos",
    exp1_location: "São Paulo, Brazil · Hybrid",
    exp1_desc: "Working as a Systems Intern in Observability Management, integrated into the B2C Emergency Response Team (ERT). Focused on high availability, critical systems monitoring, automation, incident management, and SRE best practices.",
    exp1_t1: "Creation and optimization of <strong>alarms and dashboards</strong> in ServiceNow, Elastic, and Zabbix.",
    exp1_t2: "Monitoring of mission-critical systems and <strong>metrics/logs analysis</strong> for rapid fault identification.",
    exp1_t3: "Active participation in <strong>B2C critical incident responses</strong>, supporting root cause investigations.",
    exp1_t4: "Conducting <strong>Root Cause Analysis (RCA)</strong> for recurring platform failures.",
    exp1_t5: "Managing and analyzing <strong>Problem Records (PRBs)</strong> to prevent repeated system downtime.",
    exp1_t6: "Developing automated <strong>critical incident notification workflows</strong>.",
    exp1_t7: "Web tooling and utility development using <strong>HTML, CSS, and JavaScript</strong>.",
    exp1_t8: "Engineering an <strong>automated Health Check tool</strong> for continuous server availability validation.",
    exp1_t9: "Building monitoring solutions for <strong>WebLogic application servers and task queues</strong>.",
    exp1_t10: "Operational environment administration with <strong>Oracle DB and Jenkins CI/CD</strong>.",
    exp1_t11: "Executing <strong>Stop/Start procedures, cache clearance, and log verifications</strong> in production.",
    exp1_t12: "Building SharePoint portals for <strong>production project management and technical enablement</strong>.",
    exp1_t13: "Developing web interfaces to align <strong>Project Managers, Operations, and Product Owners</strong>.",
    exp1_t14: "Acting as a point of reference for <strong>PRB quality standards</strong> through audits and team training.",
    exp1_t15: "Building custom <strong>automation tools to streamline operational workflows</strong>.",
    exp2_role: "Young Apprentice - Systems Infrastructure (PCP)",
    exp2_period: "Sep 2023 – Mar 2025 · 1 yr 7 mos",
    exp2_location: "São Paulo, Brazil · Hybrid",
    exp2_desc: "First technical role at Vivo within Systems Infrastructure in the Command Center (PCP B2C). Built solid knowledge in monitoring, infrastructure support, incident analysis, and critical platform operations.",
    exp2_t1: "B2C environment monitoring using <strong>Grafana, Dynatrace, Elastic, Kibana, Splunk, and Zabbix</strong>.",
    exp2_t2: "Deep-dive <strong>metrics, events, and log analysis</strong> for fault isolation.",
    exp2_t3: "Batch job processing and schedule tracking using <strong>Control-M</strong>.",
    exp2_t4: "System access control and reporting using <strong>SiTef Web</strong>.",
    exp2_t5: "Incident and request processing via <strong>ServiceNow</strong> platform.",
    exp2_t6: "Performing <strong>daily operational checklists</strong> to ensure environment stability.",
    exp2_t7: "Monitoring <strong>Number Portability Recovery jobs on Linux systems</strong>.",
    exp2_t8: "Queue processing validation across <strong>São Paulo and national telecom hubs</strong>.",
    exp2_t9: "Node and component validation for <strong>Siebel CRM platforms</strong>.",
    exp2_t10: "Incident escalation and real-time <strong>operational alert communications</strong>.",
    exp2_t11: "Problem troubleshooting leveraging <strong>system logs and performance KPIs</strong>.",
    exp2_t12: "Drafting technical documentation, automation scripts, and SOPs.",
    exp2_t13: "Onboarding and <strong>mentoring new team members</strong> on internal systems.",
    exp2_t14: "Operating <strong>Linux CLI environments</strong> for log extraction and recovery procedures.",
    exp2_t15: "Tracking platform health status to support continuous business operations.",
    footer_rights: "© 2026 • Portfolio of Kauê Rodrigues Mirom • IT • São Paulo, Brazil",
    lang_btn_title: "Change Language",
    back_to_top: "Back to top"
  },
  // Adicione esta continuação no objeto 'fr' dentro do script.js
  fr: {
    // ... (Manter as chaves da Parte 1) ...

    // Seção Sobre mim
    about_p1: "Mon parcours dans le domaine des Technologies de l'Information a commencé par ma formation technique en Informatique et TI chez Megatoc, où j'ai acquis mes bases en développement, infrastructure, systèmes et support technique.",
    about_p2: "Au cours de mes environ <strong>3 ans d'expérience chez Vivo (Telefônica Brasil)</strong>, j'ai débuté comme Jeune Apprenti en Infrastructure Système au Command Center (Production B2C), évoluant ensuite vers un poste de Stagiaire Système dans la Direction d'Observabilité, au sein de l'<strong>Emergency Response Team (ERT)</strong>.",
    about_p3: "Durant ce parcours, j'ai travaillé dans des <strong>environnements de production critiques</strong>, développant une expertise en observabilité, supervision, réponse aux incidents, analyse de logs, gestion des problèmes, automatisation et pratiques <strong>SRE (Site Reliability Engineering)</strong>.",
    about_p4: "Mon approche combine des connaissances en <strong>développement logiciel, infrastructure, observabilité et automatisation</strong>, visant à transformer les processus opérationnels en solutions plus efficaces, fiables et évolutives.",
    about_p5: "Actuellement, je me spécialise en <strong>Génie Logiciel</strong>, en approfondissant mes compétences en développement Full-Stack, architecture système, Cloud, bases de données, sécurité, méthodologies agiles et <strong>Intelligence Artificielle</strong>.",
    about_p6: "Mon objectif est de continuer à évoluer à l'intersection entre le <strong>Logiciel, le SRE, l'Observabilité, l'Automatisation et le Cloud</strong>, en utilisant la technologie pour résoudre des problèmes réels et accroître la fiabilité des systèmes.",

    // Seção Formação
    edu_title: "Formation",
    edu_c1_inst: "Universidade Nove de Julho",
    edu_c1_title: "Technologue en Analyse et Développement de Systèmes",
    edu_c1_period: "janv. 2025 – août 2027",
    edu_c1_p1: "Formation axée sur l'<strong>analyse, le développement et la mise en œuvre de systèmes informatiques</strong>, offrant des bases solides en programmation, génie logiciel, modélisation de données et architecture système.",
    edu_c1_p2: "Au cours de mes études, j'ai réalisé des projets académiques et pratiques en utilisant des technologies telles que <strong>Java, Python et SQL</strong>.",
    edu_c1_p3: "J'ai également développé des connaissances en <strong>Scrum et Kanban</strong> appliquées à la gestion de projet et au travail collaboratif.",
    edu_c1_p4: "La formation aborde aussi l'<strong>Intelligence Artificielle, le développement mobile et la sécurité de l'information</strong>.",
    edu_skills_title: "Compétences clés :",
    edu_c1_k1: "Programmation et développement de systèmes",
    edu_c1_k2: "Java, Python et SQL",
    edu_c1_k3: "Modélisation et bases de données",
    edu_c1_k4: "Génie logiciel et architecture",
    edu_c1_k5: "Scrum et Kanban",
    edu_c1_k6: "Résolution de problèmes informatiques",
    edu_c1_k7: "Développement de projets logiciels",
    edu_c1_k8: "Intelligence Artificielle et nouvelles technologies",
    edu_c1_k9: "Développement mobile",
    edu_c1_k10: "Sécurité de l'information",

    edu_c2_inst: "Cruzeiro do Sul Virtual",
    edu_c2_title: "Baccalauréat en Génie Logiciel",
    edu_c2_period: "janv. 2026 – déc. 2029",
    edu_c2_p1: "Ma formation en <strong>Génie Logiciel</strong> vise à approfondir les compétences techniques et maîtriser l'ensemble du <strong>cycle de vie du développement logiciel (SDLC)</strong>.",
    edu_c2_p2: "Le programme couvre les concepts d'<strong>architecture système évolutive, développement Full-Stack, Cloud Computing, bases de données, qualité, sécurité et IA</strong>.",
    edu_areas_title: "Domaines de connaissances principaux :",
    edu_c2_k1: "<strong>Développement Full-Stack :</strong> applications Web et Mobiles, Front-End, Back-End et bonnes pratiques.",
    edu_c2_k2: "<strong>Données et Systèmes :</strong> modélisation, bases de données, Science des Données.",
    edu_c2_k3: "<strong>Architecture et Cloud :</strong> bases du Cloud Computing, haute disponibilité et résilience.",
    edu_c2_k4: "<strong>Qualité et Sécurité :</strong> tests logiciels, performances et fiabilité.",
    edu_c2_k5: "<strong>Méthodologies et Gestion :</strong> gestion agile avec Scrum et Kanban.",
    edu_c2_k6: "<strong>Intelligence Artificielle :</strong> Prompt Engineering et applications d'IA pour l'automatisation.",
    edu_c2_p3: "Au cours de cette formation, j'ai développé un <strong>outil d'automatisation pour la surveillance de la santé des environnements de production</strong> (serveurs WebLogic et files d'attente).",
    edu_c2_p4: "Ce projet a transformé une inspection manuelle en une routine automatisée rapide.",
    edu_kpi_title: "Résultat et Impact (KPI)",
    edu_kpi_val: "1 heure → 5 minutes",
    edu_kpi_desc: "Réduction d'environ <strong>92% du temps d'inspection</strong> grâce à l'exécution automatisée.",
    edu_skills_dev: "Compétences développées :",
    edu_c2_s1: "Design d'interfaces (UX/UI)",
    edu_c2_s2: "Cloud Computing",
    edu_c2_s3: "Tests Logiciels — Unitaires et Fonctionnels",
    edu_c2_s4: "Planification et Architecture Système",
    edu_c2_s5: "Développement Front-End et Back-End",
    edu_c2_s6: "Automatisation de Systèmes",
    edu_c2_s7: "Qualité Logicielle",
    edu_c2_s8: "Sécurité des Applications",
    edu_c2_s9: "Intelligence Artificielle",
    edu_c2_s10: "Méthodologies Agiles",

    // Seção Cursos
    courses_title: "Formations & Certifications",
    courses_p1: "J'ai suivi plusieurs formations complémentaires sur des plateformes réputées comme <strong>Alura</strong>, <strong>Fundação Bradesco</strong>, <strong>LinkedIn Learning</strong>, <strong>Enabley UK & ROI</strong>, <strong>Vivae</strong> et via <strong>Vivo (Telefônica Brasil)</strong>.",
    courses_topics_title: "Principaux sujets étudiés :",
    courses_t1: "<strong>Programmation et Développement :</strong> JavaScript, POO Java, Git/GitHub, API et CI/CD.",
    courses_t2: "<strong>Infrastructure et DevOps :</strong> PowerShell, Docker, Linux, ServiceNow, Zabbix, Elastic et Datadog.",
    courses_t3: "<strong>Orchestration et Conteneurs :</strong> Kubernetes (Pods, Services, Deployments).",
    courses_t4: "<strong>Bases de Données :</strong> Fondations SQL et gestion des données.",
    courses_t5: "<strong>Méthodologies Agiles & Soft Skills :</strong> Scrum/Kanban, gestion du stress et soft skills.",
    courses_t6: "<strong>Bases de la TI :</strong> Réseaux mobiles, SDLC et architectures applicatives.",
    courses_p2: "Ces formations renforcent mon engagement envers l'apprentissage continu et l'efficacité opérationnelle.",

    // Seção Experiência
    exp_title: "Expérience",
    exp1_role: "Stagiaire Système - Observabilité & ERT (SRE)",
    exp1_period: "mars 2025 – présent · 1 an et 7 mois",
    exp1_location: "São Paulo, Brésil · Hybride",
    exp1_desc: "Stagiaire au sein de la Direction d'Observabilité, membre de l'équipe de réponse d'urgence B2C (ERT). Focus sur la fiabilité des environnements critiques, l'observabilité, l'automatisation et l'analyse d'incidents.",
    exp1_t1: "Création et évolution d'<strong>alarmes et dashboards</strong> sous ServiceNow, Elastic et Zabbix.",
    exp1_t2: "Surveillance d'environnements critiques et analyse de <strong>métriques, événements et logs</strong>.",
    exp1_t3: "Participation à la <strong>réponse aux incidents critiques B2C</strong>.",
    exp1_t4: "Analyse des causes racines <strong>(RCA)</strong> pour résoudre les problèmes récurrents.",
    exp1_t5: "Gestion et suivi des <strong>PRB (Problem Records)</strong>.",
    exp1_t6: "Développement de <strong>workflows d'alerte critique</strong>.",
    exp1_t7: "Développement d'automatisations web avec <strong>HTML, CSS et JavaScript</strong>.",
    exp1_t8: "Création d'un <strong>Health Check automatisé</strong> pour vérifier les serveurs.",
    exp1_t9: "Solutions pour le suivi des <strong>serveurs WebLogic et files d'attente</strong>.",
    exp1_t10: "Administration opérationnelle avec <strong>Oracle Server et Jenkins</strong>.",
    exp1_t11: "Procédures de <strong>Stop/Start, purge de cache et analyse de logs</strong> en production.",
    exp1_t12: "Création de SharePoint pour la gestion de projets et la formation.",
    exp1_t13: "Création d'outils web pour faciliter l'intégration entre Projets et Opérations.",
    exp1_t14: "Référent sur la <strong>qualité des PRB</strong> (analyses, retours et formations).",
    exp1_t15: "Automatisation et optimisation des processus opérationnels.",

    exp2_role: "Jeune Apprenti - Infrastructure Système (PCP)",
    exp2_period: "sept. 2023 – mars 2025 · 1 an et 7 mois",
    exp2_location: "São Paulo, Brésil · Hybride",
    exp2_desc: "Première expérience en TI au Command Center B2C chez Vivo. Développement de bases solides en supervision, infrastructure et support aux environnements critiques.",
    exp2_t1: "Supervision B2C via <strong>Grafana, Dynatrace, Elastic, Kibana, Splunk et Zabbix</strong>.",
    exp2_t2: "Analyse de <strong>métriques, événements et logs</strong>.",
    exp2_t3: "Gestion des traitements et jobs sous <strong>Control-M</strong>.",
    exp2_t4: "Gestion des rapports et accès via <strong>SiTef Web</strong>.",
    exp2_t5: "Traitement des tickets et incidents sous <strong>ServiceNow</strong>.",
    exp2_t6: "Réalisation des <strong>checklists opérationnelles quotidiennes</strong>.",
    exp2_t7: "Suivi des processus de <strong>Recovery de Portabilité sur Linux</strong>.",
    exp2_t8: "Supervision des files d'attente pour São Paulo et le reste du Brésil.",
    exp2_t9: "Validation des <strong>composants et nœuds Siebel</strong>.",
    exp2_t10: "Escalade et communication des <strong>alertes opérationnelles</strong>.",
    exp2_t11: "Analyse des logs pour appuyer la recherche de la cause racine.",
    exp2_t12: "Création et mise à jour de documentations et procédures.",
    exp2_t13: "Formation et intégration des nouveaux collaborateurs.",
    exp2_t14: "Exploitation d'<strong>environnements Linux</strong> pour l'analyse de logs.",
    exp2_t15: "Suivi de la santé globale des plateformes.",

    footer_rights: "© 2026 • Portfolio de Kauê Rodrigues Mirom • TI • São Paulo, Brésil"
  }
  // Cole estas chaves dentro do objeto 'fr' no seu script.js
  
  // Página: Projetos (project.html)
  projects_title: "Projets & Automatisations",
  projects_intro: "Découvrez ici quelques-uns des principaux projets et automatisations développés pour optimiser les processus opérationnels, la surveillance et l'efficacité des systèmes.",
  proj1_title: "Santé & Surveillance des Serveurs (Health Check)",
  proj1_desc: "Outil automatisé développé pour la validation de la santé des serveurs WebLogic et le suivi des files d'attente de traitement en temps réel.",
  proj1_feat1: "Automatisations d'inspection réduisant le temps d'exécution de 1 heure à 5 minutes.",
  proj1_feat2: "Tableau de bord personnalisé pour la visualisation rapide des métriques d'état et de disponibilité.",
  proj1_feat3: "Alertes préventives pour l'équipe SRE et d'exploitation.",

  proj2_title: "SharePoint & Portail de Gestion Opérationnelle",
  proj2_desc: "Portail centralisé développé pour la gestion des projets en production, le partage de connaissances et l'intégration entre les équipes.",
  proj2_feat1: "Amélioration de la communication entre les équipes de Projet, d'Exploitation et les PO (Product Owners).",
  proj2_feat2: "Espace dédié à la formation initiale et à la montée en compétences des collaborateurs.",
  proj2_feat3: "Standardisation des flux et de la documentation sur la qualité des PRB (Problem Records).",

  // Página: Habilidades Técnicas (habilidades.html)
  skills_page_title: "Compétences Techniques",
  skills_page_intro: "Un aperçu détaillé des technologies, outils et méthodologies que je maîtrise et utilise au quotidien.",
  skill_cat_obs: "Observabilité & Supervision",
  skill_cat_auto: "Automatisation & DevOps",
  skill_cat_dev: "Développement & Bases de données",
  skill_cat_infra: "Infrastructure & Systèmes",

  // Página: Conquistas (conquistas.html)
  achieve_title: "Réalisations & Jalons",
  achieve_intro: "Principaux jalons professionnels et reconnaissances obtenues au cours de mon parcours en Technologie.",
  achieve_1_year_title: "1 An de Parcours chez Vivo",
  achieve_1_year_desc: "Célébration d'une année d'impact, de croissance et de contributions aux environnements critiques et à l'observabilité.",
  achieve_kpi_title: "Réduction des Temps d'Inspection (KPI)",
  achieve_kpi_desc: "Optimisation majeure des processus grâce à l'automatisation, réduisant de 92 % le temps d'analyse des serveurs.",

  // Página: Contato (contact.html)
  contact_title: "Entretons en Contact",
  contact_intro: "Vous souhaitez discuter d'opportunités, de collaborations ou en savoir plus sur mes projets ? Envoyez-moi un message !",
  contact_form_name: "Nom complet",
  contact_form_email: "Adresse e-mail",
  contact_form_msg: "Votre message",
  contact_form_btn: "Envoyer le message",

  // Modais e Auxiliares
  lang_btn_title: "Changer de langue",
  back_to_top: "Retour en haut"


    
  
